### ISSUE TITLE
Make metadata into an OrderedDict

### ISSUE THREAD

**Issue by blais** [beancount/beancount#420]
**[Original report](https://bitbucket.org/blais/beancount/issue/420) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

I’m wondering whether it would be possible to make metadata \(both on transactions and postings\) into an OrderedDict.

I have written an importer which basically does something like:

```
            meta = data.new_metadata(f.name, index)
            meta['donor_name'] = get_name(row)
            meta['donor_email'] = row['Email']
```

It makes sense to have name first, email second, but currently beancounts sorts the keys and email comes out first.

Can you think of any disadvantages of using an OrderedDict? If not, maybe I can try to see if I can contribute a patch.

‌

**Comment by blais** [comment]
**Original comment by Daniele Nicolodi (Bitbucket: [daniele](https://bitbucket.org/daniele), GitHub: [dnicolodi](https://github.com/dnicolodi)).**

----------------------------------------

Since Python 3.6 dictionaries preserve insertion order \(and the behavior is part of the specification since Python 3.7\), thus, assuming a fairly recent Python interpreter, there is no need to change the type of the metadata object. However, metadata fields are sorted when serialized. Changing the output of the serialization, may be considered a backward incompatible change, thus, I think that disabling sorting should be an option and not the default.

It is not difficult however to monkey patch the `write_metadata` method in your importer script.

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

> Changing the output of the serialization, may be considered a backward incompatible change

Right, that’s why I wanted to file the ticket so we can talk about it.  I don’t see much of a downside of changing the behaviour. I can’t see anything depending on it being sorted, but of course I might be wrong.

> It is not difficult however to monkey patch the write\_metadata method in your importer script.

True, I’d like to avoid it if possible though.

**Comment by blais** [comment]
Agreed with @tbm newer Python dict implementation naturally handles that in ingestion framework. This should handle @dnicolodi original issue (let me know if it doesn't).
In v3 I'll make sure the metadata is using a list of (key, value) pairs in protobuf (and not protobuf::map which is slower), so they will be ordered naturally.

**Comment by dnicolodi** [comment]
Hi @blais, I think you swapped the user handles in your reply, or I don't understand it (the original issue is by @tbm). The sort on serialization (in `write_metadata`) still does not make it possible to write metadata in benacount format to a file without loosing the original order of the field. Am I misunderstanding something?

**Comment by blais** [comment]
The problem is likely that they're explicitly sorted here:
https://github.com/beancount/beancount/blob/master/beancount/parser/printer.py#L135
Removing this and writing a test that checks that the order or insertion is maintained would probably fix your issue.

We'd have to also bump the minimum version to 3.7 (fine with me) because that's the first version the ordering can be relied upon.

**Comment by zacchiro** [comment]
I'm still missing the user feature of not reordering dictionaries. I've a canonical ordering for metadata that I want to appear in my Beancount ledger, and AFAICT it is currently impossible to implement it with importers due to this issue. Can we reopen this?

I understand this bug report was closed because the proposed *implementation* (using OrderedDict) had issues. If that's the problem, I can file a dedicated issue for the missing user feature (no matter how we want to implement it).

**Comment by blais** [comment]
Stefano: Specifically where does reordering not occur? When you print (using the printer, as Daniele suggests, where fields are explicitly sorted)?  Or elsewhere? Another issue is that pickling possibly doesn't preserve order. The cache uses a Python pickle.

The problem with making the change is that there's no guarantee where the metadata gets created; OTOH, I do think that 99.9% if not 100% of the time it is manufactured by a call to new_metadata() so in theory it could just be done there. Problem is, the insertion order may actually look a little ugly when rendered from the printer depending on how it was created, and this might also break the round-trip guarantee (I'm not sure). You can try making a patch (change new_metadata and remove sorting in the printer) and see if it does what you'd like it to do.

Because of these rabbit holes, I'm a bit reluctant to spend time on this in v2, and would rather defer the issue to v3 (I'm defining the type of it now actually, which brought me back here).

**Comment by zacchiro** [comment]
You made me look into my rabbit hole related to this (i.e., my importer code :-)), and in fact it turns out my issue is probably more about the lack of an interface to *define* a specific order than it is about actual *reordering* (which might *also* be happening, but I'm no longer sure of at this point).

My importer code is just adding key/value pairs to the `.meta` attributes of Beancount entry objects.
Those metadata are later on printed (by bean-extract), I'm guessing in the usual arbitrary Python order for printing dictionaries.

So I guess my question/feature need here is along the lines of: what is the right API that importer code should use to define the order they want for metadata entries? Maybe it exists and I'm not using it; maybe it doesn't exist; or maybe it does exist but reordering happen later making it moot.

> Because of these rabbit holes, I'm a bit reluctant to spend time on this in v2, and would rather defer the issue to v3 (I'm defining the type of it now actually, which brought me back here).

Oh, I don't particularly about this being backported to v2. I just didn't want to lose in implementation details what I think is a legitimate feature request. If it's best to make this available only starting with v3, so be it.

**Comment by tbm** [comment]
> My importer code is just adding key/value pairs to the .meta attributes of Beancount entry objects.
> Those metadata are later on printed (by bean-extract), I'm guessing in the usual arbitrary Python order for printing dictionaries.

Currently beancount requires Python 3.6 so there's no guarantee of dict order.  Also, beancount explicitly sorts the keys when printing.

So I think the idea (if we wanted to change this for v2) was to:

* Change requirement to Python 3.7 to get dict order
* Remove the explicit sorting

Then you'd have stable order depending on the order you add.  That would be the "API".

**Comment by blais** [comment]
You know me, always happy to bump up the required version :-)

**Comment by zacchiro** [comment]
I've now revisited this and I can confirm that, with recent Python, just removing the `sorted()` invocation in the metadata printer fixes the issue (as in: allows importers to set the desired metadata ordering).
With #726 I'm addressing this for v2 and also bumping minimum Python version to 3.7 so that there is a guarantee that importer code can rely on this behavior.
