### ISSUE TITLE
Invalid reference to inactive account

### ISSUE THREAD

**Issue by iliveforfun** [beancount/beancount#464]
such error shown on my fava-website, though **it can work and show the correct result**, but i still need a way to solve this problem

**Comment by blais** [comment]
I don't understand your ticket. This error message indicates an error in your ledger file, you're referring to an account you've indicated is closed.

**Comment by OrangeSodahub** [comment]
> such error shown on my fava-website, though **it can work and show the correct result**, but i still need a way to solve this problem

Have you solved that problem? It happen to me, too.

**Comment by dnicolodi** [comment]
Without more context this error report is not actionable. I suspect there is an error in your input file. Can you provide a minimal example that reproduces the problem?

**Comment by ygregw** [comment]
In my case, I have two plugins declared in the "preamble":

1. beancount.plugins.split_expenses "Alice Bob Carol"
2. beancount.plugins.auto_accounts

And if the declaring order is reversed, I would get the said error for, say, the two following directives:
```
2021-10-01 * "Costco" ""
  Expenses:HandSoap                                  13.21 CAD
  Income:Alice

2021-11-01 * "Costco" ""
  Expenses:HandSoap:Alice                            13.21/2 CAD
  Expenses:HandSoap:Bob                              13.21/2 CAD
  Income:Alice
```
If split_expenses was declared before auto_accounts, however, it runs fine.

**Comment by blais** [comment]
Use bean-query print <filename> with the two orderings and diff the outputs and share here.
Plugins have to run in *some* order, and I suspect that's creating the problem.
split_expenses, for instance, is pretty special and you have to understand what it does to your transactions in order to make sense of the error.

**Comment by ygregw** [comment]
Hereby full content of the test ledger:
```
;; Let Beancount open expense accounts automatically
plugin "beancount.plugins.auto_accounts"
;; Expenses are splitted equally
plugin "beancount.plugins.split_expenses" "Alice Bob Carol"

option "operating_currency" "CAD"

2021-10-01 * "Costco" "For three"
  Expenses:Something                           9.00 CAD
  Income:Alice

2021-11-01 * "Costco" "For two"
  Expenses:Something:Alice                     10.00/2 CAD
  Expenses:Something:Bob                       10.00/2 CAD
  Income:Alice
```

Thanks for the **bean-query print** trick!  Hereby the results:

The order that generates the said error: _**auto_accounts -> split_expenses**_
```
2021-10-01 open Expenses:Something:Carol
2021-10-01 open Expenses:Something
2021-10-01 open Income:Alice

2021-10-01 * "Costco" "For three"
  Expenses:Something:Alice   3.00 CAD
  Expenses:Something:Bob     3.00 CAD
  Expenses:Something:Carol   3.00 CAD
  Income:Alice              -9.00 CAD

2021-11-01 open Expenses:Something:Alice
2021-11-01 open Expenses:Something:Bob

2021-11-01 * "Costco" "For two"
  Expenses:Something:Alice    5.00 CAD
  Expenses:Something:Bob      5.00 CAD
  Income:Alice              -10.00 CAD
```

The order that runs fine:  _**split_expenses -> auto_accounts**_
```
2021-10-01 open Expenses:Something:Bob
2021-10-01 open Expenses:Something:Alice
2021-10-01 open Expenses:Something:Carol
2021-10-01 open Income:Alice

2021-10-01 * "Costco" "For three"
  Expenses:Something:Alice   3.00 CAD
  Expenses:Something:Bob     3.00 CAD
  Expenses:Something:Carol   3.00 CAD
  Income:Alice              -9.00 CAD

2021-11-01 * "Costco" "For two"
  Expenses:Something:Alice    5.00 CAD
  Expenses:Something:Bob      5.00 CAD
  Income:Alice              -10.00 CAD
```

**Comment by blais** [comment]
Yep that makes sense to me. split_expenses creates a bunch of accounts. auto_accounts then picks them up and automates the creation of directives. Normal. If you run it the other way, auto_accounts doesn't see the split accounts created by split_expenses and doesn't create e.g. Expenses:Somthing:Carol.

I have to say I'm a bit surprised it doesn't create Expenses:Something:Bob though, since you do have that in the original file, that should have been picked up. Hmm.

**Comment by johnmee** [comment]
Take

```
2016-06-25 open Expenses:Household:Utilities
2016-06-25 open Expenses:Household:Utilities:Electricity
2016-06-25 open Expenses:Household:Utilities:Gas
```

I do have postings against both `Expenses:Household:Utilities` and `Expenses:Household:Utilities:Electricity`.

With the 'documents' option and a parent directory specified for auto generation of document tags...

The directory structure of `/mnt/drive/documents/Expenses/Household/Electricity/` causes no trouble, but does not pick up the documents.  

When I move the directory to `/mnt/drive/documents/Expenses/Household/Utilities/Electricity` this error (invalid reference..) appears.

All was fine, until today I realized some of my documents did not have a document tag autogenerated for them.  Some do.
Well, of course, that must be because the directory structure is not laid out the same way as the accounts structure.  So I rearranged the broken directories to match and suddenly this error appears everywhere.

Is it because I have Postings to both the parent and the children?
There might be a clue in the number of error messages that appear in fava.  tbc.
