### ISSUE TITLE
QUESTION: How to partially divert expenses as described in cookbook?

### ISSUE THREAD

**Issue by Akuukis** [beancount/beancount#474]
In cookbook ["How We Share Expenses"](https://docs.google.com/document/d/1RaondTJCS_IUPBHFNdT8oqFKJjVJDsfsn6JEjBG04eA/edit#heading=h.cbvs0rkc81ug) it's written:

> Whenever I incur an expense that is for both of us, I book it normally but I will tag it with #carolyn:
> 2018-12-23 * "WHISK" "Water refill" #carolyn
> ```
>   Liabilities:US:Amex:BlueCash  -32.66 USD
>   Expenses:Food:Grocery
> ```
> This gets automatically converted to:
> ```
> 2018-12-23 * "WHISK" "Water refill" #carolyn
>   Liabilities:US:Amex:BlueCash  -32.66 USD
>   Expenses:Food:Grocery          19.60 USD
>   Assets:US:Share:Carolyn       13.06 USD
>     share: TRUE
> ```
> This is done by the beancount.plugins.divert_expenses plugin. In this example, 40% of 32.66 (13.06) gets rerouted to her account. Note that this is an asset account for me, because she owes this.

I checked the [`beancount.plugins.divert_expenses`](../blob/master/beancount/plugins/divert_expenses.py) plugin and it doesn't look like it supports partial diverts as described in cookbook. How to do that?

P.S. I tried to comment on Google Docs as suggested in README but commenting seemed disabled there.

**Comment by blais** [comment]
re. google docs: Comments are disabled due to too many fat-finger /
accidental edits. I'll enable when Google has a solution for this.

re. partial diverts (e.g., 40%) there's an error in this text: it's not the
divert_expenses plugin that does this, it's another custom plugin that I
have. I realize now I never had time to publish it. You can build something
similar by hand (mine is something like 150 lines of Python, really
simple). I'll update the document.

**Comment by Akuukis** [comment]
Thanks for clarification. I will build my own then and will try to make it generic enough so it can be published.

Could you please share your custom code, in full or redacted, as a starting point?

**Comment by blais** [comment]
Something like this:
http://furius.ca/tmp/share/share.py
