### ISSUE TITLE
Categorization issue with plugin

### ISSUE THREAD

**Issue by jes-carr** [beancount/beancount#541]
I'm working on a new plugin that transfer the cost basis to a different account: https://github.com/jesucarr/beancount_cost_transfer

It is a common practice when trading cryptocurrency to transfer the commodity to your own wallet, and then back to the exchange, and it'd be useful to keep the cost basis. It is very tedious to specify the lots manually, but it seems that at the moment it is the only way. 

Without the plugin I need to do:

`

          option "booking_method" "FIFO"

          2015-01-01 open Assets:Exchange
          2015-01-01 open Assets:Wallet
          2015-01-01 open Assets:Bank
          2015-01-01 open Expenses:Something
          2015-09-04 * "Buy some bitcoins"
            Assets:Exchange       4 BTC {250 USD, 2015-09-04}
            Assets:Bank          -1000.00 USD
          2015-09-05 * "Buy some more bitcoins"
            Assets:Exchange       2 BTC {300 USD, 2015-09-05}
            Assets:Bank          -600.00 USD
          2015-09-10 * "Move to wallet"
            Assets:Exchange       -5 BTC {}
            Assets:Wallet         4 BTC {250 USD, 2015-09-04}
            Assets:Wallet         1 BTC {300 USD, 2015-09-05} 
          2015-09-11 * "Move to exchange"
            Assets:Wallet       -5 BTC {}
            Assets:Exchange         4 BTC {250 USD, 2015-09-04}
            Assets:Exchange         1 BTC {300 USD, 2015-09-05} `

With the plugin I want to add those augmentations automatically, using the same lots as the reduction:

`

          option "booking_method" "FIFO"

          2015-01-01 open Assets:Exchange
          2015-01-01 open Assets:Wallet
          2015-01-01 open Assets:Bank
          2015-01-01 open Expenses:Something
          2015-09-04 * "Buy some bitcoins"
            Assets:Exchange       4 BTC {250 USD, 2015-09-04}
            Assets:Bank          -1000.00 USD
          2015-09-05 * "Buy some more bitcoins"
            Assets:Exchange       2 BTC {300 USD, 2015-09-05}
            Assets:Bank          -600.00 USD
          2015-09-10 C "Move to wallet" ; C flags the transaction as cost transfer
            Assets:Exchange       -5 BTC {} 
            Assets:Wallet        
          2015-09-11 C "Move to exchange"
            Assets:Wallet       -5 BTC {}       
            Assets:Exchange `

The "Move to wallet" transaction seems to work as expected. However for the "Move to exchange" transaction I get the error "Failed to categorize posting 1". It seems that it can't find the lots like when the same transactions as output by the plugin are written manually. From the docs I see that the validation is done after the plugins modifications, so I think it shouldn't fail. Is there anything I'm missing?

You can replicate just running the test.py provided.

Thank you in advance.

**Comment by redstreet** [comment]
https://groups.google.com/g/beancount/c/xhNGZNRScX8

**Comment by redstreet** [comment]
No plugin needed:
```
2015-09-10 C "Move to wallet" ; C flags the transaction as cost transfer
  Assets:Exchange       -5 BTC
  Assets:Wallet        

2015-09-11 C "Move to exchange"
  Assets:Wallet       -5 BTC
  Assets:Exchange
```

**Comment by blais** [comment]
RedS: I think he wants the cost basis handled.

This transaction
```
      2015-09-10 C "Move to wallet" ; C flags the transaction as cost transfer
        Assets:Exchange       -5 BTC {} 
        Assets:Wallet        
```
will fill in the weight of the first postings on the second leg, not the lots.
Print out the expanded context of the transaction (bean-doctor context) to see what it parses into.

**Comment by redstreet** [comment]
Got it, my bad. Sorry @jesucarr, the above won't work, see @blais ' response instead.

@blais: I'm curious, this is unexpected: how is it that the BTC in Assets:Exchange end up with the right cost basis, as long as exactly the same number of BTC (5 in this case) is transferred back and forth?

```
Input file: "Beancount"
Ready with 8 directives (8 postings in 4 transactions).
beancount> print
2015-01-01 open Assets:Exchange
2015-01-01 open Assets:Wallet
2015-01-01 open Assets:Bank
2015-01-01 open Expenses:Something

2015-09-04 * "Buy some bitcoins"
  Assets:Exchange         4 BTC {250 USD, 2015-09-04}
  Assets:Bank      -1000.00 USD

2015-09-05 * "Buy some more bitcoins"
  Assets:Exchange        2 BTC {300 USD, 2015-09-05}
  Assets:Bank      -600.00 USD

2015-09-10 C "Move to wallet"
  Assets:Exchange  -5 BTC
  Assets:Wallet     5 BTC

2015-09-11 C "Move to exchange"
  Assets:Wallet    -5 BTC
  Assets:Exchange   5 BTC
beancount> balances
    account           sum_position
--------------- -------------------------
Assets:Bank     -1600.00 USD
Assets:Exchange     4    BTC {250    USD},     2    BTC {300    USD}
Assets:Wallet
```

**Comment by jes-carr** [comment]
@redstreet that's a good point. I didn't notice that happens, but indeed I also wouldn't expect that to happen. Hopefully Martin can clarify.

@blais here is the bean-doctor context:

    
```

------------ Balances before transaction

  Assets:Exchange                        4 BTC {250 USD, 2015-09-04}
  Assets:Exchange                        2 BTC {300 USD, 2015-09-05}

  Assets:Wallet                                                     


------------ Transaction

2015-09-10 C "Move to wallet"
  Assets:Exchange  -4 BTC {250.00 USD, 2015-09-04}  ; -1000 USD
  Assets:Exchange  -1 BTC {300.00 USD, 2015-09-05}  ;  -300 USD
  Assets:Wallet     4 BTC {250.00 USD, 2015-09-04}  ;  1000 USD
  Assets:Wallet     1 BTC {300.00 USD, 2015-09-05}  ;   300 USD



------------ Balances after transaction

* Assets:Exchange                        1 BTC {300 USD, 2015-09-05}

* Assets:Wallet                          4 BTC {250 USD, 2015-09-04}
* Assets:Wallet                          1 BTC {300 USD, 2015-09-05}


```

so it's all as expected so far. The problem is with the next transaction:

```
2015-09-11 C "Move to exchange"
  Assets:Wallet       -5 BTC {}       
  Assets:Exchange 
```

It fails to categorize, as if it weren't able to find the cost basis in Assets:Wallet.

**Comment by blais** [comment]
Okay so I'm looking at this in a bit more detail now. Long response.

@jesucarr: First, about your original problem.
First, I assume you understand that without your plugin, what would get transferred to wallet on 9/10 is just the cash cost basis (no lots). So if that were the case, that's precisely the error you would get, i.e. if your plugin wasn't enabled somehow.

But I downloaded your code, and that's not quite what's going on.
What's happening is that when there is an error on that last transaction, and when that happens, the transaction is not produced.
(In fact, this is a really annoying bug, because it prevents you from running context on it, and so I've been thinking about ways to change that and leave in some partially filled transaction. TBD.  It's not obvious though, because the output of the plugins is supposed to be fully resolved, and so leaving transactions with missing bits will break all sorts of other codes which assumes completely interpolated and booked postings.)
If you change your plugin to print the transactions it catches to process, you will find that it does not process the last one, for that reason (run pytest -s).

The problem is that Beancount attempts to book transactions before your plugins run.
When I wrote the v3 doc and I mentioned that the distinction between "after parsing" and "after booking", the two stream of transactions internally, wasn't super clearly explained, and that's related. Really there ought to be two types of plugins: ones that run after the simple parsing, on completely unbooked, uninterpolated transactions, allowing this through, and allow your plugin to modify them at that point, and ones that run on the result of that, doing the full booking and interpolation. In that world, your plugin would be of the former type. FWIW, in v3 they will be streams with two distinct data types (one of the things that makes it more confusing in v2 is that they're the same datatypes, except that the parser output is using CostSpec instead of Cost on Postings, and allows MISSING values; anyhow, I disgres).

Now, if you can only avoid triggering an error in the first place, that might work for this plugin.
If I change the last transaction to -5 BTC {USD}, if has enough information to figure out that the final leg is USD, so that categorization error goes away (this is what "categorization" means, when you just say -5 BTC {}, first it needs to figure out what currency group to balance this with, in this case, USD, so you can just tell it, like that).
But then, there's another error, which is that there aren't enough numbers supplied for interpolation to succeed (it can only interpolate a single number per categorized currency group).

If you wrote
```
          2015-09-11 C "Move to exchange"                                                                                                                                                                                                                                                                                                                                                                                               
            Assets:Wallet       -5 BTC {}                                                                                                                                                                                                                                                                                                                                                                                               
            Assets:Exchange    0 USD                                                                                                                                                                                                                                                                                                                                                                                                    
```
the transaction goes through, and you could change your plugin to process it and fixup the 0.
It's not pretty.

```
          2015-09-11 C "Move to exchange"                                                                                                                                                                                                                                                                                                                                                                                               
            Assets:Wallet       -5 BTC {USD}                                                                                                                                                                                                                                                                                                                                                                                               
```
would also let it through and it's a bit better, but then you can't specify the other account.
I suppose the account could be specified in the plugin configuration, if there's ever only one account.

I'm afraid I don't have a great solution for this. v3 plugins will be revised to allow stuff like that.

**Comment by jes-carr** [comment]
Thanks for detailing the current limitations. 

I did try your last suggestion, specifying the account in the plugin (you can see the new commit). However I indeed need multiple accounts, so I'm doing that in a meta. Looks like this:

```
2015-09-11 C "Move to exchange"
  account: Assets:Exchange
  Assets:Wallet       -5 BTC {USD}   
```

The transaction goes through, but it still fails to pick up the 4+1 lots stored in Assets:Wallet from the previous transaction.

```
------------ Balances before transaction

  Assets:Wallet                          4 BTC {250 USD, 2015-09-04}
  Assets:Wallet                          1 BTC {300 USD, 2015-09-05}

  Assets:Exchange                        1 BTC {300 USD, 2015-09-05}


------------ Transaction

2015-09-11 C "Move to exchange"
  account: "Assets:Exchange"
  Assets:Wallet    -5 BTC {-0.00 USD, 2015-09-11}  ;  0 USD
  Assets:Exchange   5 BTC {-0.00 USD, 2015-09-11}  ; -0 USD



------------ Balances after transaction

  Assets:Wallet                          4 BTC {250 USD, 2015-09-04}
  Assets:Wallet                          1 BTC {300 USD, 2015-09-05}
* Assets:Wallet                          -5 BTC {-0 USD, 2015-09-11}

  Assets:Exchange                        1 BTC {300 USD, 2015-09-05}
* Assets:Exchange                         5 BTC {-0 USD, 2015-09-11}
```

Did I miss anything?

**Comment by blais** [comment]
I haven't been able to look at it, but I suspect the last transaction will fail because it depends on matching on the contents of the inventory before it, and the correct contents of that inventory won't be computed at the time it does its matching because they'd only be filled in by your modified transaction.

I think you'll probably really need the pure parsing plugin I described in my explanation. I'm not sure what you're attempting to do is doable with the current version.

**Comment by jes-carr** [comment]
Ok understood. 

What would be ideal is a new syntax in v3 that allows such lot transfer natively. It could look like this:

```
2015-09-10 * "Move to wallet" 
        Assets:Exchange       -5 BTC {} 
        Assets:Wallet         {}
```

Would you consider to add support for lot transfer natively (with that syntax or with a different syntax that you find more appropriate)?
