### ISSUE TITLE
Can I make a balance assertion about market value?

### ISSUE THREAD

**Issue by AakashM0** [beancount/beancount#604]
I have an investment account (as background information, it's non-taxable so I use the NONE booking method) in which I buy units of a mutual fund. My broker provides an account summary which lists my current holding, latest market price, and current market value. I can enter a `balance` assertion to confirm that my file agrees with my broker in respect of the number of units of the fund.

I also put the latest price into my beancount file with a `price` directive. Can I use a `balance` assertion to confirm that my file agrees with my broker in respect of the current market value?

Example:

```
option "operating_currency" "GBP"
plugin "beancount.plugins.unrealized" "Unrealized"
plugin "beancount.plugins.implicit_prices"

* Commodities
2012-09-07 commodity GBP
  name: "Pound Sterling"

2012-09-07 commodity B41XG30
  name: "Vanguard LifeStrategy 100% Equity Accumulation (GBP)"
  
* Accounts
2012-09-07 open Assets:ISA 
2012-09-07 open Assets:ISA:Cash GBP
2012-09-07 open Assets:ISA:B41XG30 B41XG30 "NONE"
2012-09-07 open Income:BankAccount:2783		GBP


* Transactions

;topup
2012-09-07 * "REG. SAVER // Transfer From Bank Account Bank A/C : ****2783"
  Assets:ISA:Cash 75 GBP
  Income:BankAccount:2783
  
;purchase
2012-09-10 *   "B346530501 // Vanguard LifeStrategy 100% Equity Accumulation (GBP) .7242 @  10356.66380"
  Assets:ISA:B41XG30 0.7242 B41XG30 { 103.56638 GBP }
  Assets:ISA:Cash -75.00 GBP
  
; final price point
2021-01-07 price B41XG30 260.188 GBP

; balance assertion about units held
2021-01-07 balance Assets:ISA:B41XG30 0.7242 B41XG30

; balance assertion about market value - doesn't work, want to find out how to do this 
2021-01-07 balance Assets:ISA 188.43 GBP
```

With the above file, both bean_web and fava know that the market value of `Assets:ISA` is 188.43 GBP - is there a way I can assert this fact within the beancount file itself?

**Comment by dnicolodi** [comment]
This is currently not supported, see here https://beancount.github.io/docs/balance_assertions_in_beancount.html. Beancount balance assertions are "partial balances", namely they assert that the specified account contains exactly the specified amount of a given commodity, without conversions. There are plans (see the document above) for implementing "total balances" but nothing has materialized in the code yet. I think "total balances" can be implemented as a plugin.

Finally, support requests are better directed to the mailing list rather than on this issue tracker.

**Comment by AakashM0** [comment]
Thanks, and apologies for the mispost. Reposted (with answer) to the mailing list for posterity: https://groups.google.com/g/beancount/c/Gj1wF6cTnbo
