### ISSUE TITLE
Document directives scanner only accepts A–Z, a–z, ß, æ, ø directory names

### ISSUE THREAD

**Issue by sefsh** [beancount/beancount#750]
### Description of Issue

Using a documents option to generate document journal entries from a directory, as in [https://beancount.github.io/docs/beancount_language_syntax.html#documents-from-a-directory ](https://beancount.github.io/docs/beancount_language_syntax.html#documents-from-a-directory) works only if accounts and therefore its subsequent directory names are written in the character ranges of A–Z and a–z. The rest of Beancount (and Fava) works fine with nordic and german characters, emojis etc.

### Software versions used for testing

    beancount==2.3.5
    fava==1.24

### Other software used:

    VSCodium 1.76.1
    Firefox 110.0.1 (1 (64-bit)
    macOS 13

### Steps to reproduce

1. Create this file as `test.bean`
```
option "documents" "docs"
option "operating_currency" "THARNI"

2020-01-01 open Assets:Cash
2020-01-01 open Liabilities:Debts

2023-03-14 * "Pippin" "Settle debt"
  document: "2020-01-01.ProofOfPippin.jpg"
  Assets:Cash        -100 THARNI
  Liabilities:Debts   100 THARNI
```
2. Create the directory structure: `mkdir -p docs/Assets/Cash`
3. Add a file to it: `touch docs/Assets/Cash/2020-01-01.ProofOfPippin.jpg`
4. Run `bean-report test.bean print`. Output:
```
2020-01-01 open Assets:Cash
2020-01-01 open Liabilities:Debts

2020-01-01 document Assets:Cash "/Users/sef/docs/Assets/Cash/2020-01-01.ProofOfPippin.jpg"

2023-03-14 * "Pippin" "Settle debt"
  document: "2020-01-01.ProofOfPippin.jpg"
  Assets:Cash        -100 THARNI
  Liabilities:Debts   100 THARNI

```
5. **Now "Break it"**
6. Adapt `Cash` to the local tongue: `Cäsh`:
```
option "documents" "docs"
option "operating_currency" "THARNI"

2020-01-01 open Assets:Cäsh
2020-01-01 open Liabilities:Debts

2023-03-14 * "Pippin" "Settle debt"
  document: "2020-01-01.ProofOfPippin.jpg"
  Assets:Cäsh        -100 THARNI
  Liabilities:Debts   100 THARNI
```
7. Rename directory: `mv docs/Assets/Cash docs/Assets/Cäsh`
8. Run `bean-report test.bean print` again. Output:
```
2020-01-01 open Assets:Cäsh
2020-01-01 open Liabilities:Debts

2023-03-14 * "Pippin" "Settle debt"
  document: "2020-01-01.ProofOfPippin.jpg"
  Assets:Cäsh        -100 THARNI
  Liabilities:Debts   100 THARNI
```

As we can see Beancount accepts this account name, but cannot traverse directories replicating this naming, or at least it doesn't produce a document directive in the end. Document scanning breaks if accounts are using for example `å`, `ä`, `ö`, `ü`, `·` in their names. Oddly enough `ß`, `æ`, `ø` works fine.

(This issue started out in https://github.com/beancount/fava/issues/1480)

**Comment by dnicolodi** [comment]
The issue is due to this regular expression https://github.com/beancount/beancount/blob/5e04ec4b857aa3a18362cce8759dc7814b949ce4/beancount/core/account.py#L27-L36 not matching some non-ascii character correctly.

The `re` module in the Python standard library does not support Unicode character classes, thus we have some emulation for that in `beancount.utils.regexp_utils`. The emulation mostly works but has some limitations. One limitation is that it does not handle Unicode characters in decomposed form (there is more than one way to represent the same Unicode character, there is some explanation in the `unicodedata` Python standard library module). Python uses the normal form for representing string, thus the account name as written in the ledger file is validated correctly. However, the macOS filesystem uses canonical decomposition form, and the machinery that generates `document` directives from the filesystem does not recognize the directory name as a valid account name. Normalizing the Unicode string to NFC form before matching it against the regular expression solves the issue.

**Comment by sefsh** [comment]
Are the results of this regular expression usually used in plugins, or do plugins parse account names on their own?

**Comment by dnicolodi** [comment]
I don't understand what you mean. Plugins operate on the parsed ledger, thus they don't need to match account names. However, plugins can use these regular expressions or beancount functions that use them to do what they are supposed to be doing.

**Comment by sefsh** [comment]
Sorry. I asked this because the beancount autofill plugin threw an error on an account name that Beancount itself found valid.

**Comment by mikaeljagelid** [comment]
I have to agree with OP here. I also find it strange that unicode characters are allowed and functioning (almost) everywhere else but in folder names for Documents. The limitations explained above is apparently not affecting the use of unicode characters in account names, but only for folder names and account types.

**Comment by dnicolodi** [comment]
@yusf I have submitted a patch for this issue in #775. I think I was able to reproduce the issue on my macOS system, but I was unable to reproduce it when working on the patch. Which OS are you working on (name and version)? Can you test whether #775 solved the issue?

**Comment by sefsh** [comment]
Great! Will try #775 🙌 
Will this patch make it into v2 as well?
