### ISSUE TITLE
Accounting equation violation

### ISSUE THREAD

**Issue by tczajka** [beancount/beancount#764]
I am sure this is a known issue. But I couldn't find a ticket addressing this.

The [documentation](https://beancount.github.io/docs/the_double_entry_counting_method.html) claims:
```
A + L + E + X + I = 0
```
and then it provides a "proof":

> This follows from the fact that
> ```sum(all postings) = 0```
> Which follows from the fact that each transaction is guaranteed to sum up to zero (**which is enforced by Beancount**):
> ```for all transactions t, sum(postings of t) = 0```

However, this doesn't actually work:
```
2023-01-01 open Assets:Checking:USD
2023-01-01 open Assets:Checking:EUR
2023-01-01 open Equity:Opening-Balances

2023-06-15 * "Opening balances"
  Assets:Checking:USD    100 USD
  Equity:Opening-Balances

2023-07-01 * "Buy Euro"
  Assets:Checking:EUR   50 EUR @ 2 USD
  Assets:Checking:USD   -100 USD

2023-07-15 * "Sell Euro"
  Assets:Checking:USD   150 USD
  Assets:Checking:EUR   -50 EUR @ 3 USD
```

```
$ bean-report a.beancount balances
Assets:Checking:EUR     
Assets:Checking:USD        150 USD
Equity:Opening-Balances   -100 USD
Expenses                
Income                  
Liabilities             
```

**Comment by blais** [comment]
This is well known, this is due to the way price conversions are handled.
If you "close" at a particular date, a transaction - the only one that breaks the accounting equation - will be inserted automatically to restore this balance.
Long term a solution is to implement Peter Selinger's transfer accounts. This is something v3 should eventually do, that is, automatically insert postings to currency accounts to account for these differences.
