### ISSUE TITLE
new new v2 version for py311 windows pypi wheel

### ISSUE THREAD

**Issue by trim21** [beancount/beancount#778]
https://pypi.org/project/beancount/#files

lastest v2 version is released before python3.11 is released, so we didn't build beancount 2.3.5 py311 wheel.

Can we have a new v2 release to trigger ci to release a new version for new python version?

**Comment by blais** [comment]
I have no idea who does this. I don't handle Windows.

**Comment by dnicolodi** [comment]
For the last release we had CI jobs to produce Windows wheels and upload to PyPI. If we want to have another v2 release with the fixes than have been merged since the last release I can refresh the setup for building and publishing wheels. Most likely, in addition to Python 3.11 we want to build for 3.12 as well. 

Before a new release I would like to make sure than all fixes that went into master are also in the v2 branch and the other way around. However, it makes sense to think whether we want to keep pushing fixes to both branches. I would be in favor of releasing a 2.4.0 version (or 2.90.0, or whatever) from master and go back to care about only one branch.

**Comment by dnicolodi** [comment]
The patch that makes beancount work with Python 3.12 would be the fist candidate for a backport from master to v2.

**Comment by blais** [comment]
Do you mean backport just the changes to the setup?
That SGTM.
(Code changes not so much, I'm sure you'll agree.)

**Comment by dnicolodi** [comment]
> Do you mean backport just the changes to the setup?

beancount from the v2 branch does not work on Python 3.12. It is a trivial fix: https://github.com/beancount/beancount/commit/d5923d25206b569c678f4bc664468769084dd866

**Comment by blais** [comment]
Thanks Daniele, I added this fix manually just now and pushed.

**Comment by trim21** [comment]
> I have no idea who does this. I don't handle Windows.

Pypi wheels is handled by ci。

**Comment by dnicolodi** [comment]
@blais I saw that you pushed a new release tag. The CI job for building wheel has not been updated to include the latest Python releases, thus wheels for Python 3.10, 3.11, and 3.12 are still missing.

**Comment by blais** [comment]
Sorry guys, I can't fix this soon. If you care about a Windows wheel, please backport the setup from the master feature and send me a PR, I'll rubberstamp it.
