### ISSUE TITLE
Transaction not exported by beancount/api.py

### ISSUE THREAD

**Issue by yonil7** [beancount/beancount#894]
For some reason `Transaction` is not "exported" (as "public" API) by `beancount/api.py`

**Comment by blais** [comment]
https://github.com/beancount/beancount/blob/master/beancount/api.py#L44

**Comment by alexrkaufman** [comment]
I came across this issue while trying to refactor the beangulp importers I have built to use the public beancount api. As I understand it beangulp importers' `extract` function must return a list of Directives. In order to do this I have to create `Transaction` and `Balance` directives while running the extraction which requires importing those objects from `beancount.core` rather than the public api. 

I do not understand the response that closed the comment since it seems like if I am generating a`Posting` I will at some point need to put it in a `Transaction`. This makes me think I am misunderstanding something so please let me know if I am just doing something wrong or my mental model is off. 

Current state:
```python
import beangulp
from beancount.core import data

class Importer(beangulp.Importer):
    # other functions etc. 
    def extract(self, filepath, existing):
        entries = []
        # extracting stuff 
        entries.append(data.Transaction(...))
        # extracting stuff 
        return entries
# etc. 
```

Expected state with beancount api:
```python
import beangulp
import beancount as bn

class Importer(beangulp.Importer):
    # other functions etc. 
    def extract(self, filepath, existing):
        entries = []
        # extracting stuff 
        entries.append(bn.Transaction(...))
        # extracting stuff 
        return entries
# etc. 
```

Its not a huge difference but I was surprised not to find the `Transaction` or `Balance` directives in the beancount api.

I greatly appreciate the work on this project and would be happy to contribute wherever needed.

**Comment by blais** [comment]
bn.dtypes.Transaction
Maybe I should just attach them at the root, might be simpler

**Comment by alexrkaufman** [comment]
Ah! I see now and just saw your commit. I appreciate your help here. I think putting them on the root will be a little bit more discoverable.

Thank you again for this project it is very cool and has been immeasurably helpful.
